[package]
name = "bus_prototype"
version = "0.1.0"
edition = "2021"

[dependencies]
kdtree = "0.6.0"
serde = { version = "1.0.152", features=["derive"] }
serde_json = "1.0.91"
fs-err = "2.9.0"
rayon = "1.8.1"
smallvec = { version = "1.10.0", features=["serde"] }
rand = "0.8.5"
anyhow = "1.0.79"
